const actionTypesContacts = {
  INIT_CONTACTS_START: 'INIT_CONTACTS_START',
  INIT_CONTACTS_SUCCESS: 'INIT_CONTACTS_SUCCESS',
  INIT_CONTACTS_ERROR: 'INIT_CONTACTS_ERROR',

  EDIT_CONTACT_START: 'EDIT_CONTACT_START',
  EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',

  DELETE_CONTACT_START: 'DELETE_CONTACT_START',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',

  ADD_CONTACT_START: 'ADD_CONTACT_START',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
}
export default actionTypesContacts;
