const actionTypesContacts = {
  INIT_CONTACTS_START: 'INIT_CONTACTS_START',
  INIT_CONTACTS_SUCCESS: 'INIT_CONTACTS_SUCCESS',
  INIT_CONTACTS_ERROR: 'INIT_CONTACTS_ERROR',

  ADD_CONTACT_START: 'ADD_CONTACT_START',

  DELETE_CONTACT_START: 'DELETE_CONTACT_START',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_ERROR: 'DELETE_CONTACT_ERROR',

  EDIT_CONTACT_START: 'EDIT_CONTACT_START',
}
export default actionTypesContacts;
